/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as MainIndexRouteImport } from './routes/_main.index'
import { Route as MainAboutRouteImport } from './routes/_main.about'
import { Route as MainDashboardRouteImport } from './routes/_main.dashboard'
import { Route as MainForgotPasswordRouteImport } from './routes/_main.forgot-password'
import { Route as MainLoginRouteImport } from './routes/_main.login'
import { Route as MainMembersRouteImport } from './routes/_main.members'
import { Route as MainMessagesRouteImport } from './routes/_main.messages'
import { Route as MainNotificationsRouteImport } from './routes/_main.notifications'
import { Route as MainProfileRouteImport } from './routes/_main.profile'
import { Route as MainRegisterRouteImport } from './routes/_main.register'
import { Route as MainResetPasswordRouteImport } from './routes/_main.reset-password'
import { Route as MainSecurityRouteImport } from './routes/_main.security'
import { Route as MainVerifyEmailRouteImport } from './routes/_main.verify-email'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as ApiEvaluationsRouteImport } from './routes/api.evaluations'
import { Route as ApiNotificationsRouteImport } from './routes/api.notifications'
import { Route as ApiProjectsRouteImport } from './routes/api.projects'
import { Route as ApiUsersRouteImport } from './routes/api.users'
import { Route as MainMembersIdRouteImport } from './routes/_main.members.$id'
import { Route as MainProjectsIndexRouteImport } from './routes/_main.projects.index'
import { Route as MainProjectsProjectIdRouteImport } from './routes/_main.projects.$projectId'
import { Route as MainProjectsCreateRouteImport } from './routes/_main.projects.create'
import { Route as MainVerifyEmailTokenRouteImport } from './routes/_main.verify-email.$token'
import { Route as ApiAdminDashboardRouteImport } from './routes/api.admin.dashboard'
import { Route as ApiAdminLogsRouteImport } from './routes/api.admin.logs'
import { Route as ApiAdminUsersRouteImport } from './routes/api.admin.users'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as ApiEvaluationsIdRouteImport } from './routes/api.evaluations.$id'
import { Route as ApiNotificationsMarkReadRouteImport } from './routes/api.notifications.mark-read'
import { Route as ApiNotificationsStreamRouteImport } from './routes/api.notifications.stream'
import { Route as ApiNotificationsUnreadCountRouteImport } from './routes/api.notifications.unread-count'
import { Route as ApiProjectsIdRouteImport } from './routes/api.projects.$id'
import { Route as ApiProjectsSearchRouteImport } from './routes/api.projects.search'
import { Route as ApiUsersIdRouteImport } from './routes/api.users.$id'
import { Route as ApiUsersAvatarRouteImport } from './routes/api.users.avatar'
import { Route as ApiUsersMessagesRouteImport } from './routes/api.users.messages'
import { Route as ApiUsersProfileRouteImport } from './routes/api.users.profile'
import { Route as ApiUsersSearchRouteImport } from './routes/api.users.search'
import { Route as MainProjectsProjectIdEditRouteImport } from './routes/_main.projects.$projectId_.edit'
import { Route as ApiAdminUsersIdRouteImport } from './routes/api.admin.users.$id'
import { Route as ApiProjectsIdCollaborateRouteImport } from './routes/api.projects.$id.collaborate'
import { Route as ApiProjectsIdCommentsRouteImport } from './routes/api.projects.$id.comments'
import { Route as ApiProjectsIdEvaluationsRouteImport } from './routes/api.projects.$id.evaluations'
import { Route as ApiProjectsIdJoinRouteImport } from './routes/api.projects.$id.join'
import { Route as ApiProjectsIdLeaveRouteImport } from './routes/api.projects.$id.leave'
import { Route as ApiProjectsIdReposRouteImport } from './routes/api.projects.$id.repos'
import { Route as ApiProjectsUserUserIdRouteImport } from './routes/api.projects.user.$userId'
import { Route as ApiUsersAvatarIdRouteImport } from './routes/api.users.avatar.$id'
import { Route as ApiUsersMessagesIdRouteImport } from './routes/api.users.messages.$id'
import { Route as ApiUsersProfileImageRouteImport } from './routes/api.users.profile.image'
import { Route as ApiUsersProfileMeRouteImport } from './routes/api.users.profile.me'
import { Route as ApiAdminUsersIdRoleRouteImport } from './routes/api.admin.users.$id.role'
import { Route as ApiAdminUsersIdSuspensionRouteImport } from './routes/api.admin.users.$id.suspension'
import { Route as ApiGithubReposOwnerNameRouteImport } from './routes/api.github.repos.$owner.$name'
import { Route as ApiProjectsIdCollaborateUserIdRouteImport } from './routes/api.projects.$id.collaborate.$userId'
import { Route as ApiProjectsIdCommentsCommentIdRouteImport } from './routes/api.projects.$id.comments.$commentId'
import { Route as ApiProjectsIdReposRepoIdRouteImport } from './routes/api.projects.$id.repos.$repoId'
import { Route as ApiUsersMessagesIdReadRouteImport } from './routes/api.users.messages.$id.read'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainAboutRoute = MainAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MainRoute,
} as any)
const MainDashboardRoute = MainDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => MainRoute,
} as any)
const MainForgotPasswordRoute = MainForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => MainRoute,
} as any)
const MainLoginRoute = MainLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => MainRoute,
} as any)
const MainMembersRoute = MainMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => MainRoute,
} as any)
const MainMessagesRoute = MainMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => MainRoute,
} as any)
const MainNotificationsRoute = MainNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => MainRoute,
} as any)
const MainProfileRoute = MainProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MainRoute,
} as any)
const MainRegisterRoute = MainRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => MainRoute,
} as any)
const MainResetPasswordRoute = MainResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => MainRoute,
} as any)
const MainSecurityRoute = MainSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => MainRoute,
} as any)
const MainVerifyEmailRoute = MainVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => MainRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const ApiEvaluationsRoute = ApiEvaluationsRouteImport.update({
  id: '/api/evaluations',
  path: '/api/evaluations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsRoute = ApiNotificationsRouteImport.update({
  id: '/api/notifications',
  path: '/api/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const MainMembersIdRoute = MainMembersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MainMembersRoute,
} as any)
const MainProjectsIndexRoute = MainProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => MainRoute,
} as any)
const MainProjectsProjectIdRoute = MainProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => MainRoute,
} as any)
const MainProjectsCreateRoute = MainProjectsCreateRouteImport.update({
  id: '/projects/create',
  path: '/projects/create',
  getParentRoute: () => MainRoute,
} as any)
const MainVerifyEmailTokenRoute = MainVerifyEmailTokenRouteImport.update({
  id: '/$token',
  path: '/$token',
  getParentRoute: () => MainVerifyEmailRoute,
} as any)
const ApiAdminDashboardRoute = ApiAdminDashboardRouteImport.update({
  id: '/api/admin/dashboard',
  path: '/api/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLogsRoute = ApiAdminLogsRouteImport.update({
  id: '/api/admin/logs',
  path: '/api/admin/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEvaluationsIdRoute = ApiEvaluationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiEvaluationsRoute,
} as any)
const ApiNotificationsMarkReadRoute =
  ApiNotificationsMarkReadRouteImport.update({
    id: '/mark-read',
    path: '/mark-read',
    getParentRoute: () => ApiNotificationsRoute,
  } as any)
const ApiNotificationsStreamRoute = ApiNotificationsStreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => ApiNotificationsRoute,
} as any)
const ApiNotificationsUnreadCountRoute =
  ApiNotificationsUnreadCountRouteImport.update({
    id: '/unread-count',
    path: '/unread-count',
    getParentRoute: () => ApiNotificationsRoute,
  } as any)
const ApiProjectsIdRoute = ApiProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiProjectsRoute,
} as any)
const ApiProjectsSearchRoute = ApiProjectsSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ApiProjectsRoute,
} as any)
const ApiUsersIdRoute = ApiUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiUsersRoute,
} as any)
const ApiUsersAvatarRoute = ApiUsersAvatarRouteImport.update({
  id: '/avatar',
  path: '/avatar',
  getParentRoute: () => ApiUsersRoute,
} as any)
const ApiUsersMessagesRoute = ApiUsersMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => ApiUsersRoute,
} as any)
const ApiUsersProfileRoute = ApiUsersProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ApiUsersRoute,
} as any)
const ApiUsersSearchRoute = ApiUsersSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ApiUsersRoute,
} as any)
const MainProjectsProjectIdEditRoute =
  MainProjectsProjectIdEditRouteImport.update({
    id: '/projects/$projectId_/edit',
    path: '/projects/$projectId/edit',
    getParentRoute: () => MainRoute,
  } as any)
const ApiAdminUsersIdRoute = ApiAdminUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminUsersRoute,
} as any)
const ApiProjectsIdCollaborateRoute =
  ApiProjectsIdCollaborateRouteImport.update({
    id: '/collaborate',
    path: '/collaborate',
    getParentRoute: () => ApiProjectsIdRoute,
  } as any)
const ApiProjectsIdCommentsRoute = ApiProjectsIdCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => ApiProjectsIdRoute,
} as any)
const ApiProjectsIdEvaluationsRoute =
  ApiProjectsIdEvaluationsRouteImport.update({
    id: '/evaluations',
    path: '/evaluations',
    getParentRoute: () => ApiProjectsIdRoute,
  } as any)
const ApiProjectsIdJoinRoute = ApiProjectsIdJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => ApiProjectsIdRoute,
} as any)
const ApiProjectsIdLeaveRoute = ApiProjectsIdLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => ApiProjectsIdRoute,
} as any)
const ApiProjectsIdReposRoute = ApiProjectsIdReposRouteImport.update({
  id: '/repos',
  path: '/repos',
  getParentRoute: () => ApiProjectsIdRoute,
} as any)
const ApiProjectsUserUserIdRoute = ApiProjectsUserUserIdRouteImport.update({
  id: '/user/$userId',
  path: '/user/$userId',
  getParentRoute: () => ApiProjectsRoute,
} as any)
const ApiUsersAvatarIdRoute = ApiUsersAvatarIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiUsersAvatarRoute,
} as any)
const ApiUsersMessagesIdRoute = ApiUsersMessagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiUsersMessagesRoute,
} as any)
const ApiUsersProfileImageRoute = ApiUsersProfileImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => ApiUsersProfileRoute,
} as any)
const ApiUsersProfileMeRoute = ApiUsersProfileMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => ApiUsersProfileRoute,
} as any)
const ApiAdminUsersIdRoleRoute = ApiAdminUsersIdRoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => ApiAdminUsersIdRoute,
} as any)
const ApiAdminUsersIdSuspensionRoute =
  ApiAdminUsersIdSuspensionRouteImport.update({
    id: '/suspension',
    path: '/suspension',
    getParentRoute: () => ApiAdminUsersIdRoute,
  } as any)
const ApiGithubReposOwnerNameRoute = ApiGithubReposOwnerNameRouteImport.update({
  id: '/api/github/repos/$owner/$name',
  path: '/api/github/repos/$owner/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsIdCollaborateUserIdRoute =
  ApiProjectsIdCollaborateUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => ApiProjectsIdCollaborateRoute,
  } as any)
const ApiProjectsIdCommentsCommentIdRoute =
  ApiProjectsIdCommentsCommentIdRouteImport.update({
    id: '/$commentId',
    path: '/$commentId',
    getParentRoute: () => ApiProjectsIdCommentsRoute,
  } as any)
const ApiProjectsIdReposRepoIdRoute =
  ApiProjectsIdReposRepoIdRouteImport.update({
    id: '/$repoId',
    path: '/$repoId',
    getParentRoute: () => ApiProjectsIdReposRoute,
  } as any)
const ApiUsersMessagesIdReadRoute = ApiUsersMessagesIdReadRouteImport.update({
  id: '/read',
  path: '/read',
  getParentRoute: () => ApiUsersMessagesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/about': typeof MainAboutRoute
  '/dashboard': typeof MainDashboardRoute
  '/forgot-password': typeof MainForgotPasswordRoute
  '/login': typeof MainLoginRoute
  '/members': typeof MainMembersRouteWithChildren
  '/messages': typeof MainMessagesRoute
  '/notifications': typeof MainNotificationsRoute
  '/profile': typeof MainProfileRoute
  '/register': typeof MainRegisterRoute
  '/reset-password': typeof MainResetPasswordRoute
  '/security': typeof MainSecurityRoute
  '/verify-email': typeof MainVerifyEmailRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/evaluations': typeof ApiEvaluationsRouteWithChildren
  '/api/notifications': typeof ApiNotificationsRouteWithChildren
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/api/users': typeof ApiUsersRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/members/$id': typeof MainMembersIdRoute
  '/projects/$projectId': typeof MainProjectsProjectIdRoute
  '/projects/create': typeof MainProjectsCreateRoute
  '/verify-email/$token': typeof MainVerifyEmailTokenRoute
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
  '/api/admin/logs': typeof ApiAdminLogsRoute
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/evaluations/$id': typeof ApiEvaluationsIdRoute
  '/api/notifications/mark-read': typeof ApiNotificationsMarkReadRoute
  '/api/notifications/stream': typeof ApiNotificationsStreamRoute
  '/api/notifications/unread-count': typeof ApiNotificationsUnreadCountRoute
  '/api/projects/$id': typeof ApiProjectsIdRouteWithChildren
  '/api/projects/search': typeof ApiProjectsSearchRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/api/users/avatar': typeof ApiUsersAvatarRouteWithChildren
  '/api/users/messages': typeof ApiUsersMessagesRouteWithChildren
  '/api/users/profile': typeof ApiUsersProfileRouteWithChildren
  '/api/users/search': typeof ApiUsersSearchRoute
  '/projects/': typeof MainProjectsIndexRoute
  '/projects/$projectId/edit': typeof MainProjectsProjectIdEditRoute
  '/api/admin/users/$id': typeof ApiAdminUsersIdRouteWithChildren
  '/api/projects/$id/collaborate': typeof ApiProjectsIdCollaborateRouteWithChildren
  '/api/projects/$id/comments': typeof ApiProjectsIdCommentsRouteWithChildren
  '/api/projects/$id/evaluations': typeof ApiProjectsIdEvaluationsRoute
  '/api/projects/$id/join': typeof ApiProjectsIdJoinRoute
  '/api/projects/$id/leave': typeof ApiProjectsIdLeaveRoute
  '/api/projects/$id/repos': typeof ApiProjectsIdReposRouteWithChildren
  '/api/projects/user/$userId': typeof ApiProjectsUserUserIdRoute
  '/api/users/avatar/$id': typeof ApiUsersAvatarIdRoute
  '/api/users/messages/$id': typeof ApiUsersMessagesIdRouteWithChildren
  '/api/users/profile/image': typeof ApiUsersProfileImageRoute
  '/api/users/profile/me': typeof ApiUsersProfileMeRoute
  '/api/admin/users/$id/role': typeof ApiAdminUsersIdRoleRoute
  '/api/admin/users/$id/suspension': typeof ApiAdminUsersIdSuspensionRoute
  '/api/github/repos/$owner/$name': typeof ApiGithubReposOwnerNameRoute
  '/api/projects/$id/collaborate/$userId': typeof ApiProjectsIdCollaborateUserIdRoute
  '/api/projects/$id/comments/$commentId': typeof ApiProjectsIdCommentsCommentIdRoute
  '/api/projects/$id/repos/$repoId': typeof ApiProjectsIdReposRepoIdRoute
  '/api/users/messages/$id/read': typeof ApiUsersMessagesIdReadRoute
}
export interface FileRoutesByTo {
  '/about': typeof MainAboutRoute
  '/dashboard': typeof MainDashboardRoute
  '/forgot-password': typeof MainForgotPasswordRoute
  '/login': typeof MainLoginRoute
  '/members': typeof MainMembersRouteWithChildren
  '/messages': typeof MainMessagesRoute
  '/notifications': typeof MainNotificationsRoute
  '/profile': typeof MainProfileRoute
  '/register': typeof MainRegisterRoute
  '/reset-password': typeof MainResetPasswordRoute
  '/security': typeof MainSecurityRoute
  '/verify-email': typeof MainVerifyEmailRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/evaluations': typeof ApiEvaluationsRouteWithChildren
  '/api/notifications': typeof ApiNotificationsRouteWithChildren
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/api/users': typeof ApiUsersRouteWithChildren
  '/': typeof MainIndexRoute
  '/admin': typeof AdminIndexRoute
  '/members/$id': typeof MainMembersIdRoute
  '/projects/$projectId': typeof MainProjectsProjectIdRoute
  '/projects/create': typeof MainProjectsCreateRoute
  '/verify-email/$token': typeof MainVerifyEmailTokenRoute
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
  '/api/admin/logs': typeof ApiAdminLogsRoute
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/evaluations/$id': typeof ApiEvaluationsIdRoute
  '/api/notifications/mark-read': typeof ApiNotificationsMarkReadRoute
  '/api/notifications/stream': typeof ApiNotificationsStreamRoute
  '/api/notifications/unread-count': typeof ApiNotificationsUnreadCountRoute
  '/api/projects/$id': typeof ApiProjectsIdRouteWithChildren
  '/api/projects/search': typeof ApiProjectsSearchRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/api/users/avatar': typeof ApiUsersAvatarRouteWithChildren
  '/api/users/messages': typeof ApiUsersMessagesRouteWithChildren
  '/api/users/profile': typeof ApiUsersProfileRouteWithChildren
  '/api/users/search': typeof ApiUsersSearchRoute
  '/projects': typeof MainProjectsIndexRoute
  '/projects/$projectId/edit': typeof MainProjectsProjectIdEditRoute
  '/api/admin/users/$id': typeof ApiAdminUsersIdRouteWithChildren
  '/api/projects/$id/collaborate': typeof ApiProjectsIdCollaborateRouteWithChildren
  '/api/projects/$id/comments': typeof ApiProjectsIdCommentsRouteWithChildren
  '/api/projects/$id/evaluations': typeof ApiProjectsIdEvaluationsRoute
  '/api/projects/$id/join': typeof ApiProjectsIdJoinRoute
  '/api/projects/$id/leave': typeof ApiProjectsIdLeaveRoute
  '/api/projects/$id/repos': typeof ApiProjectsIdReposRouteWithChildren
  '/api/projects/user/$userId': typeof ApiProjectsUserUserIdRoute
  '/api/users/avatar/$id': typeof ApiUsersAvatarIdRoute
  '/api/users/messages/$id': typeof ApiUsersMessagesIdRouteWithChildren
  '/api/users/profile/image': typeof ApiUsersProfileImageRoute
  '/api/users/profile/me': typeof ApiUsersProfileMeRoute
  '/api/admin/users/$id/role': typeof ApiAdminUsersIdRoleRoute
  '/api/admin/users/$id/suspension': typeof ApiAdminUsersIdSuspensionRoute
  '/api/github/repos/$owner/$name': typeof ApiGithubReposOwnerNameRoute
  '/api/projects/$id/collaborate/$userId': typeof ApiProjectsIdCollaborateUserIdRoute
  '/api/projects/$id/comments/$commentId': typeof ApiProjectsIdCommentsCommentIdRoute
  '/api/projects/$id/repos/$repoId': typeof ApiProjectsIdReposRepoIdRoute
  '/api/users/messages/$id/read': typeof ApiUsersMessagesIdReadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_main/about': typeof MainAboutRoute
  '/_main/dashboard': typeof MainDashboardRoute
  '/_main/forgot-password': typeof MainForgotPasswordRoute
  '/_main/login': typeof MainLoginRoute
  '/_main/members': typeof MainMembersRouteWithChildren
  '/_main/messages': typeof MainMessagesRoute
  '/_main/notifications': typeof MainNotificationsRoute
  '/_main/profile': typeof MainProfileRoute
  '/_main/register': typeof MainRegisterRoute
  '/_main/reset-password': typeof MainResetPasswordRoute
  '/_main/security': typeof MainSecurityRoute
  '/_main/verify-email': typeof MainVerifyEmailRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/evaluations': typeof ApiEvaluationsRouteWithChildren
  '/api/notifications': typeof ApiNotificationsRouteWithChildren
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/api/users': typeof ApiUsersRouteWithChildren
  '/_main/': typeof MainIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_main/members/$id': typeof MainMembersIdRoute
  '/_main/projects/$projectId': typeof MainProjectsProjectIdRoute
  '/_main/projects/create': typeof MainProjectsCreateRoute
  '/_main/verify-email/$token': typeof MainVerifyEmailTokenRoute
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
  '/api/admin/logs': typeof ApiAdminLogsRoute
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/evaluations/$id': typeof ApiEvaluationsIdRoute
  '/api/notifications/mark-read': typeof ApiNotificationsMarkReadRoute
  '/api/notifications/stream': typeof ApiNotificationsStreamRoute
  '/api/notifications/unread-count': typeof ApiNotificationsUnreadCountRoute
  '/api/projects/$id': typeof ApiProjectsIdRouteWithChildren
  '/api/projects/search': typeof ApiProjectsSearchRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/api/users/avatar': typeof ApiUsersAvatarRouteWithChildren
  '/api/users/messages': typeof ApiUsersMessagesRouteWithChildren
  '/api/users/profile': typeof ApiUsersProfileRouteWithChildren
  '/api/users/search': typeof ApiUsersSearchRoute
  '/_main/projects/': typeof MainProjectsIndexRoute
  '/_main/projects/$projectId_/edit': typeof MainProjectsProjectIdEditRoute
  '/api/admin/users/$id': typeof ApiAdminUsersIdRouteWithChildren
  '/api/projects/$id/collaborate': typeof ApiProjectsIdCollaborateRouteWithChildren
  '/api/projects/$id/comments': typeof ApiProjectsIdCommentsRouteWithChildren
  '/api/projects/$id/evaluations': typeof ApiProjectsIdEvaluationsRoute
  '/api/projects/$id/join': typeof ApiProjectsIdJoinRoute
  '/api/projects/$id/leave': typeof ApiProjectsIdLeaveRoute
  '/api/projects/$id/repos': typeof ApiProjectsIdReposRouteWithChildren
  '/api/projects/user/$userId': typeof ApiProjectsUserUserIdRoute
  '/api/users/avatar/$id': typeof ApiUsersAvatarIdRoute
  '/api/users/messages/$id': typeof ApiUsersMessagesIdRouteWithChildren
  '/api/users/profile/image': typeof ApiUsersProfileImageRoute
  '/api/users/profile/me': typeof ApiUsersProfileMeRoute
  '/api/admin/users/$id/role': typeof ApiAdminUsersIdRoleRoute
  '/api/admin/users/$id/suspension': typeof ApiAdminUsersIdSuspensionRoute
  '/api/github/repos/$owner/$name': typeof ApiGithubReposOwnerNameRoute
  '/api/projects/$id/collaborate/$userId': typeof ApiProjectsIdCollaborateUserIdRoute
  '/api/projects/$id/comments/$commentId': typeof ApiProjectsIdCommentsCommentIdRoute
  '/api/projects/$id/repos/$repoId': typeof ApiProjectsIdReposRepoIdRoute
  '/api/users/messages/$id/read': typeof ApiUsersMessagesIdReadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/members'
    | '/messages'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/security'
    | '/verify-email'
    | '/admin/analytics'
    | '/admin/logs'
    | '/admin/settings'
    | '/admin/users'
    | '/api/evaluations'
    | '/api/notifications'
    | '/api/projects'
    | '/api/users'
    | '/admin/'
    | '/members/$id'
    | '/projects/$projectId'
    | '/projects/create'
    | '/verify-email/$token'
    | '/api/admin/dashboard'
    | '/api/admin/logs'
    | '/api/admin/users'
    | '/api/auth/$'
    | '/api/evaluations/$id'
    | '/api/notifications/mark-read'
    | '/api/notifications/stream'
    | '/api/notifications/unread-count'
    | '/api/projects/$id'
    | '/api/projects/search'
    | '/api/users/$id'
    | '/api/users/avatar'
    | '/api/users/messages'
    | '/api/users/profile'
    | '/api/users/search'
    | '/projects/'
    | '/projects/$projectId/edit'
    | '/api/admin/users/$id'
    | '/api/projects/$id/collaborate'
    | '/api/projects/$id/comments'
    | '/api/projects/$id/evaluations'
    | '/api/projects/$id/join'
    | '/api/projects/$id/leave'
    | '/api/projects/$id/repos'
    | '/api/projects/user/$userId'
    | '/api/users/avatar/$id'
    | '/api/users/messages/$id'
    | '/api/users/profile/image'
    | '/api/users/profile/me'
    | '/api/admin/users/$id/role'
    | '/api/admin/users/$id/suspension'
    | '/api/github/repos/$owner/$name'
    | '/api/projects/$id/collaborate/$userId'
    | '/api/projects/$id/comments/$commentId'
    | '/api/projects/$id/repos/$repoId'
    | '/api/users/messages/$id/read'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/members'
    | '/messages'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/security'
    | '/verify-email'
    | '/admin/analytics'
    | '/admin/logs'
    | '/admin/settings'
    | '/admin/users'
    | '/api/evaluations'
    | '/api/notifications'
    | '/api/projects'
    | '/api/users'
    | '/'
    | '/admin'
    | '/members/$id'
    | '/projects/$projectId'
    | '/projects/create'
    | '/verify-email/$token'
    | '/api/admin/dashboard'
    | '/api/admin/logs'
    | '/api/admin/users'
    | '/api/auth/$'
    | '/api/evaluations/$id'
    | '/api/notifications/mark-read'
    | '/api/notifications/stream'
    | '/api/notifications/unread-count'
    | '/api/projects/$id'
    | '/api/projects/search'
    | '/api/users/$id'
    | '/api/users/avatar'
    | '/api/users/messages'
    | '/api/users/profile'
    | '/api/users/search'
    | '/projects'
    | '/projects/$projectId/edit'
    | '/api/admin/users/$id'
    | '/api/projects/$id/collaborate'
    | '/api/projects/$id/comments'
    | '/api/projects/$id/evaluations'
    | '/api/projects/$id/join'
    | '/api/projects/$id/leave'
    | '/api/projects/$id/repos'
    | '/api/projects/user/$userId'
    | '/api/users/avatar/$id'
    | '/api/users/messages/$id'
    | '/api/users/profile/image'
    | '/api/users/profile/me'
    | '/api/admin/users/$id/role'
    | '/api/admin/users/$id/suspension'
    | '/api/github/repos/$owner/$name'
    | '/api/projects/$id/collaborate/$userId'
    | '/api/projects/$id/comments/$commentId'
    | '/api/projects/$id/repos/$repoId'
    | '/api/users/messages/$id/read'
  id:
    | '__root__'
    | '/_main'
    | '/admin'
    | '/_main/about'
    | '/_main/dashboard'
    | '/_main/forgot-password'
    | '/_main/login'
    | '/_main/members'
    | '/_main/messages'
    | '/_main/notifications'
    | '/_main/profile'
    | '/_main/register'
    | '/_main/reset-password'
    | '/_main/security'
    | '/_main/verify-email'
    | '/admin/analytics'
    | '/admin/logs'
    | '/admin/settings'
    | '/admin/users'
    | '/api/evaluations'
    | '/api/notifications'
    | '/api/projects'
    | '/api/users'
    | '/_main/'
    | '/admin/'
    | '/_main/members/$id'
    | '/_main/projects/$projectId'
    | '/_main/projects/create'
    | '/_main/verify-email/$token'
    | '/api/admin/dashboard'
    | '/api/admin/logs'
    | '/api/admin/users'
    | '/api/auth/$'
    | '/api/evaluations/$id'
    | '/api/notifications/mark-read'
    | '/api/notifications/stream'
    | '/api/notifications/unread-count'
    | '/api/projects/$id'
    | '/api/projects/search'
    | '/api/users/$id'
    | '/api/users/avatar'
    | '/api/users/messages'
    | '/api/users/profile'
    | '/api/users/search'
    | '/_main/projects/'
    | '/_main/projects/$projectId_/edit'
    | '/api/admin/users/$id'
    | '/api/projects/$id/collaborate'
    | '/api/projects/$id/comments'
    | '/api/projects/$id/evaluations'
    | '/api/projects/$id/join'
    | '/api/projects/$id/leave'
    | '/api/projects/$id/repos'
    | '/api/projects/user/$userId'
    | '/api/users/avatar/$id'
    | '/api/users/messages/$id'
    | '/api/users/profile/image'
    | '/api/users/profile/me'
    | '/api/admin/users/$id/role'
    | '/api/admin/users/$id/suspension'
    | '/api/github/repos/$owner/$name'
    | '/api/projects/$id/collaborate/$userId'
    | '/api/projects/$id/comments/$commentId'
    | '/api/projects/$id/repos/$repoId'
    | '/api/users/messages/$id/read'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  ApiEvaluationsRoute: typeof ApiEvaluationsRouteWithChildren
  ApiNotificationsRoute: typeof ApiNotificationsRouteWithChildren
  ApiProjectsRoute: typeof ApiProjectsRouteWithChildren
  ApiUsersRoute: typeof ApiUsersRouteWithChildren
  ApiAdminDashboardRoute: typeof ApiAdminDashboardRoute
  ApiAdminLogsRoute: typeof ApiAdminLogsRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiGithubReposOwnerNameRoute: typeof ApiGithubReposOwnerNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/about': {
      id: '/_main/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MainAboutRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/dashboard': {
      id: '/_main/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof MainDashboardRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/forgot-password': {
      id: '/_main/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof MainForgotPasswordRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/login': {
      id: '/_main/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof MainLoginRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/members': {
      id: '/_main/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MainMembersRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/messages': {
      id: '/_main/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MainMessagesRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/notifications': {
      id: '/_main/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof MainNotificationsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/profile': {
      id: '/_main/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof MainProfileRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/register': {
      id: '/_main/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof MainRegisterRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/reset-password': {
      id: '/_main/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof MainResetPasswordRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/security': {
      id: '/_main/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof MainSecurityRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/verify-email': {
      id: '/_main/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof MainVerifyEmailRouteImport
      parentRoute: typeof MainRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/evaluations': {
      id: '/api/evaluations'
      path: '/api/evaluations'
      fullPath: '/api/evaluations'
      preLoaderRoute: typeof ApiEvaluationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications': {
      id: '/api/notifications'
      path: '/api/notifications'
      fullPath: '/api/notifications'
      preLoaderRoute: typeof ApiNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/members/$id': {
      id: '/_main/members/$id'
      path: '/$id'
      fullPath: '/members/$id'
      preLoaderRoute: typeof MainMembersIdRouteImport
      parentRoute: typeof MainMembersRoute
    }
    '/_main/projects/': {
      id: '/_main/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof MainProjectsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/projects/$projectId': {
      id: '/_main/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof MainProjectsProjectIdRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/projects/create': {
      id: '/_main/projects/create'
      path: '/projects/create'
      fullPath: '/projects/create'
      preLoaderRoute: typeof MainProjectsCreateRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/verify-email/$token': {
      id: '/_main/verify-email/$token'
      path: '/$token'
      fullPath: '/verify-email/$token'
      preLoaderRoute: typeof MainVerifyEmailTokenRouteImport
      parentRoute: typeof MainVerifyEmailRoute
    }
    '/api/admin/dashboard': {
      id: '/api/admin/dashboard'
      path: '/api/admin/dashboard'
      fullPath: '/api/admin/dashboard'
      preLoaderRoute: typeof ApiAdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/logs': {
      id: '/api/admin/logs'
      path: '/api/admin/logs'
      fullPath: '/api/admin/logs'
      preLoaderRoute: typeof ApiAdminLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/evaluations/$id': {
      id: '/api/evaluations/$id'
      path: '/$id'
      fullPath: '/api/evaluations/$id'
      preLoaderRoute: typeof ApiEvaluationsIdRouteImport
      parentRoute: typeof ApiEvaluationsRoute
    }
    '/api/notifications/mark-read': {
      id: '/api/notifications/mark-read'
      path: '/mark-read'
      fullPath: '/api/notifications/mark-read'
      preLoaderRoute: typeof ApiNotificationsMarkReadRouteImport
      parentRoute: typeof ApiNotificationsRoute
    }
    '/api/notifications/stream': {
      id: '/api/notifications/stream'
      path: '/stream'
      fullPath: '/api/notifications/stream'
      preLoaderRoute: typeof ApiNotificationsStreamRouteImport
      parentRoute: typeof ApiNotificationsRoute
    }
    '/api/notifications/unread-count': {
      id: '/api/notifications/unread-count'
      path: '/unread-count'
      fullPath: '/api/notifications/unread-count'
      preLoaderRoute: typeof ApiNotificationsUnreadCountRouteImport
      parentRoute: typeof ApiNotificationsRoute
    }
    '/api/projects/$id': {
      id: '/api/projects/$id'
      path: '/$id'
      fullPath: '/api/projects/$id'
      preLoaderRoute: typeof ApiProjectsIdRouteImport
      parentRoute: typeof ApiProjectsRoute
    }
    '/api/projects/search': {
      id: '/api/projects/search'
      path: '/search'
      fullPath: '/api/projects/search'
      preLoaderRoute: typeof ApiProjectsSearchRouteImport
      parentRoute: typeof ApiProjectsRoute
    }
    '/api/users/$id': {
      id: '/api/users/$id'
      path: '/$id'
      fullPath: '/api/users/$id'
      preLoaderRoute: typeof ApiUsersIdRouteImport
      parentRoute: typeof ApiUsersRoute
    }
    '/api/users/avatar': {
      id: '/api/users/avatar'
      path: '/avatar'
      fullPath: '/api/users/avatar'
      preLoaderRoute: typeof ApiUsersAvatarRouteImport
      parentRoute: typeof ApiUsersRoute
    }
    '/api/users/messages': {
      id: '/api/users/messages'
      path: '/messages'
      fullPath: '/api/users/messages'
      preLoaderRoute: typeof ApiUsersMessagesRouteImport
      parentRoute: typeof ApiUsersRoute
    }
    '/api/users/profile': {
      id: '/api/users/profile'
      path: '/profile'
      fullPath: '/api/users/profile'
      preLoaderRoute: typeof ApiUsersProfileRouteImport
      parentRoute: typeof ApiUsersRoute
    }
    '/api/users/search': {
      id: '/api/users/search'
      path: '/search'
      fullPath: '/api/users/search'
      preLoaderRoute: typeof ApiUsersSearchRouteImport
      parentRoute: typeof ApiUsersRoute
    }
    '/_main/projects/$projectId_/edit': {
      id: '/_main/projects/$projectId_/edit'
      path: '/projects/$projectId/edit'
      fullPath: '/projects/$projectId/edit'
      preLoaderRoute: typeof MainProjectsProjectIdEditRouteImport
      parentRoute: typeof MainRoute
    }
    '/api/admin/users/$id': {
      id: '/api/admin/users/$id'
      path: '/$id'
      fullPath: '/api/admin/users/$id'
      preLoaderRoute: typeof ApiAdminUsersIdRouteImport
      parentRoute: typeof ApiAdminUsersRoute
    }
    '/api/projects/$id/collaborate': {
      id: '/api/projects/$id/collaborate'
      path: '/collaborate'
      fullPath: '/api/projects/$id/collaborate'
      preLoaderRoute: typeof ApiProjectsIdCollaborateRouteImport
      parentRoute: typeof ApiProjectsIdRoute
    }
    '/api/projects/$id/comments': {
      id: '/api/projects/$id/comments'
      path: '/comments'
      fullPath: '/api/projects/$id/comments'
      preLoaderRoute: typeof ApiProjectsIdCommentsRouteImport
      parentRoute: typeof ApiProjectsIdRoute
    }
    '/api/projects/$id/evaluations': {
      id: '/api/projects/$id/evaluations'
      path: '/evaluations'
      fullPath: '/api/projects/$id/evaluations'
      preLoaderRoute: typeof ApiProjectsIdEvaluationsRouteImport
      parentRoute: typeof ApiProjectsIdRoute
    }
    '/api/projects/$id/join': {
      id: '/api/projects/$id/join'
      path: '/join'
      fullPath: '/api/projects/$id/join'
      preLoaderRoute: typeof ApiProjectsIdJoinRouteImport
      parentRoute: typeof ApiProjectsIdRoute
    }
    '/api/projects/$id/leave': {
      id: '/api/projects/$id/leave'
      path: '/leave'
      fullPath: '/api/projects/$id/leave'
      preLoaderRoute: typeof ApiProjectsIdLeaveRouteImport
      parentRoute: typeof ApiProjectsIdRoute
    }
    '/api/projects/$id/repos': {
      id: '/api/projects/$id/repos'
      path: '/repos'
      fullPath: '/api/projects/$id/repos'
      preLoaderRoute: typeof ApiProjectsIdReposRouteImport
      parentRoute: typeof ApiProjectsIdRoute
    }
    '/api/projects/user/$userId': {
      id: '/api/projects/user/$userId'
      path: '/user/$userId'
      fullPath: '/api/projects/user/$userId'
      preLoaderRoute: typeof ApiProjectsUserUserIdRouteImport
      parentRoute: typeof ApiProjectsRoute
    }
    '/api/users/avatar/$id': {
      id: '/api/users/avatar/$id'
      path: '/$id'
      fullPath: '/api/users/avatar/$id'
      preLoaderRoute: typeof ApiUsersAvatarIdRouteImport
      parentRoute: typeof ApiUsersAvatarRoute
    }
    '/api/users/messages/$id': {
      id: '/api/users/messages/$id'
      path: '/$id'
      fullPath: '/api/users/messages/$id'
      preLoaderRoute: typeof ApiUsersMessagesIdRouteImport
      parentRoute: typeof ApiUsersMessagesRoute
    }
    '/api/users/profile/image': {
      id: '/api/users/profile/image'
      path: '/image'
      fullPath: '/api/users/profile/image'
      preLoaderRoute: typeof ApiUsersProfileImageRouteImport
      parentRoute: typeof ApiUsersProfileRoute
    }
    '/api/users/profile/me': {
      id: '/api/users/profile/me'
      path: '/me'
      fullPath: '/api/users/profile/me'
      preLoaderRoute: typeof ApiUsersProfileMeRouteImport
      parentRoute: typeof ApiUsersProfileRoute
    }
    '/api/admin/users/$id/role': {
      id: '/api/admin/users/$id/role'
      path: '/role'
      fullPath: '/api/admin/users/$id/role'
      preLoaderRoute: typeof ApiAdminUsersIdRoleRouteImport
      parentRoute: typeof ApiAdminUsersIdRoute
    }
    '/api/admin/users/$id/suspension': {
      id: '/api/admin/users/$id/suspension'
      path: '/suspension'
      fullPath: '/api/admin/users/$id/suspension'
      preLoaderRoute: typeof ApiAdminUsersIdSuspensionRouteImport
      parentRoute: typeof ApiAdminUsersIdRoute
    }
    '/api/github/repos/$owner/$name': {
      id: '/api/github/repos/$owner/$name'
      path: '/api/github/repos/$owner/$name'
      fullPath: '/api/github/repos/$owner/$name'
      preLoaderRoute: typeof ApiGithubReposOwnerNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$id/collaborate/$userId': {
      id: '/api/projects/$id/collaborate/$userId'
      path: '/$userId'
      fullPath: '/api/projects/$id/collaborate/$userId'
      preLoaderRoute: typeof ApiProjectsIdCollaborateUserIdRouteImport
      parentRoute: typeof ApiProjectsIdCollaborateRoute
    }
    '/api/projects/$id/comments/$commentId': {
      id: '/api/projects/$id/comments/$commentId'
      path: '/$commentId'
      fullPath: '/api/projects/$id/comments/$commentId'
      preLoaderRoute: typeof ApiProjectsIdCommentsCommentIdRouteImport
      parentRoute: typeof ApiProjectsIdCommentsRoute
    }
    '/api/projects/$id/repos/$repoId': {
      id: '/api/projects/$id/repos/$repoId'
      path: '/$repoId'
      fullPath: '/api/projects/$id/repos/$repoId'
      preLoaderRoute: typeof ApiProjectsIdReposRepoIdRouteImport
      parentRoute: typeof ApiProjectsIdReposRoute
    }
    '/api/users/messages/$id/read': {
      id: '/api/users/messages/$id/read'
      path: '/read'
      fullPath: '/api/users/messages/$id/read'
      preLoaderRoute: typeof ApiUsersMessagesIdReadRouteImport
      parentRoute: typeof ApiUsersMessagesIdRoute
    }
  }
}

interface MainMembersRouteChildren {
  MainMembersIdRoute: typeof MainMembersIdRoute
}

const MainMembersRouteChildren: MainMembersRouteChildren = {
  MainMembersIdRoute: MainMembersIdRoute,
}

const MainMembersRouteWithChildren = MainMembersRoute._addFileChildren(
  MainMembersRouteChildren,
)

interface MainVerifyEmailRouteChildren {
  MainVerifyEmailTokenRoute: typeof MainVerifyEmailTokenRoute
}

const MainVerifyEmailRouteChildren: MainVerifyEmailRouteChildren = {
  MainVerifyEmailTokenRoute: MainVerifyEmailTokenRoute,
}

const MainVerifyEmailRouteWithChildren = MainVerifyEmailRoute._addFileChildren(
  MainVerifyEmailRouteChildren,
)

interface MainRouteChildren {
  MainAboutRoute: typeof MainAboutRoute
  MainDashboardRoute: typeof MainDashboardRoute
  MainForgotPasswordRoute: typeof MainForgotPasswordRoute
  MainLoginRoute: typeof MainLoginRoute
  MainMembersRoute: typeof MainMembersRouteWithChildren
  MainMessagesRoute: typeof MainMessagesRoute
  MainNotificationsRoute: typeof MainNotificationsRoute
  MainProfileRoute: typeof MainProfileRoute
  MainRegisterRoute: typeof MainRegisterRoute
  MainResetPasswordRoute: typeof MainResetPasswordRoute
  MainSecurityRoute: typeof MainSecurityRoute
  MainVerifyEmailRoute: typeof MainVerifyEmailRouteWithChildren
  MainIndexRoute: typeof MainIndexRoute
  MainProjectsProjectIdRoute: typeof MainProjectsProjectIdRoute
  MainProjectsCreateRoute: typeof MainProjectsCreateRoute
  MainProjectsIndexRoute: typeof MainProjectsIndexRoute
  MainProjectsProjectIdEditRoute: typeof MainProjectsProjectIdEditRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainAboutRoute: MainAboutRoute,
  MainDashboardRoute: MainDashboardRoute,
  MainForgotPasswordRoute: MainForgotPasswordRoute,
  MainLoginRoute: MainLoginRoute,
  MainMembersRoute: MainMembersRouteWithChildren,
  MainMessagesRoute: MainMessagesRoute,
  MainNotificationsRoute: MainNotificationsRoute,
  MainProfileRoute: MainProfileRoute,
  MainRegisterRoute: MainRegisterRoute,
  MainResetPasswordRoute: MainResetPasswordRoute,
  MainSecurityRoute: MainSecurityRoute,
  MainVerifyEmailRoute: MainVerifyEmailRouteWithChildren,
  MainIndexRoute: MainIndexRoute,
  MainProjectsProjectIdRoute: MainProjectsProjectIdRoute,
  MainProjectsCreateRoute: MainProjectsCreateRoute,
  MainProjectsIndexRoute: MainProjectsIndexRoute,
  MainProjectsProjectIdEditRoute: MainProjectsProjectIdEditRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ApiEvaluationsRouteChildren {
  ApiEvaluationsIdRoute: typeof ApiEvaluationsIdRoute
}

const ApiEvaluationsRouteChildren: ApiEvaluationsRouteChildren = {
  ApiEvaluationsIdRoute: ApiEvaluationsIdRoute,
}

const ApiEvaluationsRouteWithChildren = ApiEvaluationsRoute._addFileChildren(
  ApiEvaluationsRouteChildren,
)

interface ApiNotificationsRouteChildren {
  ApiNotificationsMarkReadRoute: typeof ApiNotificationsMarkReadRoute
  ApiNotificationsStreamRoute: typeof ApiNotificationsStreamRoute
  ApiNotificationsUnreadCountRoute: typeof ApiNotificationsUnreadCountRoute
}

const ApiNotificationsRouteChildren: ApiNotificationsRouteChildren = {
  ApiNotificationsMarkReadRoute: ApiNotificationsMarkReadRoute,
  ApiNotificationsStreamRoute: ApiNotificationsStreamRoute,
  ApiNotificationsUnreadCountRoute: ApiNotificationsUnreadCountRoute,
}

const ApiNotificationsRouteWithChildren =
  ApiNotificationsRoute._addFileChildren(ApiNotificationsRouteChildren)

interface ApiProjectsIdCollaborateRouteChildren {
  ApiProjectsIdCollaborateUserIdRoute: typeof ApiProjectsIdCollaborateUserIdRoute
}

const ApiProjectsIdCollaborateRouteChildren: ApiProjectsIdCollaborateRouteChildren =
  {
    ApiProjectsIdCollaborateUserIdRoute: ApiProjectsIdCollaborateUserIdRoute,
  }

const ApiProjectsIdCollaborateRouteWithChildren =
  ApiProjectsIdCollaborateRoute._addFileChildren(
    ApiProjectsIdCollaborateRouteChildren,
  )

interface ApiProjectsIdCommentsRouteChildren {
  ApiProjectsIdCommentsCommentIdRoute: typeof ApiProjectsIdCommentsCommentIdRoute
}

const ApiProjectsIdCommentsRouteChildren: ApiProjectsIdCommentsRouteChildren = {
  ApiProjectsIdCommentsCommentIdRoute: ApiProjectsIdCommentsCommentIdRoute,
}

const ApiProjectsIdCommentsRouteWithChildren =
  ApiProjectsIdCommentsRoute._addFileChildren(
    ApiProjectsIdCommentsRouteChildren,
  )

interface ApiProjectsIdReposRouteChildren {
  ApiProjectsIdReposRepoIdRoute: typeof ApiProjectsIdReposRepoIdRoute
}

const ApiProjectsIdReposRouteChildren: ApiProjectsIdReposRouteChildren = {
  ApiProjectsIdReposRepoIdRoute: ApiProjectsIdReposRepoIdRoute,
}

const ApiProjectsIdReposRouteWithChildren =
  ApiProjectsIdReposRoute._addFileChildren(ApiProjectsIdReposRouteChildren)

interface ApiProjectsIdRouteChildren {
  ApiProjectsIdCollaborateRoute: typeof ApiProjectsIdCollaborateRouteWithChildren
  ApiProjectsIdCommentsRoute: typeof ApiProjectsIdCommentsRouteWithChildren
  ApiProjectsIdEvaluationsRoute: typeof ApiProjectsIdEvaluationsRoute
  ApiProjectsIdJoinRoute: typeof ApiProjectsIdJoinRoute
  ApiProjectsIdLeaveRoute: typeof ApiProjectsIdLeaveRoute
  ApiProjectsIdReposRoute: typeof ApiProjectsIdReposRouteWithChildren
}

const ApiProjectsIdRouteChildren: ApiProjectsIdRouteChildren = {
  ApiProjectsIdCollaborateRoute: ApiProjectsIdCollaborateRouteWithChildren,
  ApiProjectsIdCommentsRoute: ApiProjectsIdCommentsRouteWithChildren,
  ApiProjectsIdEvaluationsRoute: ApiProjectsIdEvaluationsRoute,
  ApiProjectsIdJoinRoute: ApiProjectsIdJoinRoute,
  ApiProjectsIdLeaveRoute: ApiProjectsIdLeaveRoute,
  ApiProjectsIdReposRoute: ApiProjectsIdReposRouteWithChildren,
}

const ApiProjectsIdRouteWithChildren = ApiProjectsIdRoute._addFileChildren(
  ApiProjectsIdRouteChildren,
)

interface ApiProjectsRouteChildren {
  ApiProjectsIdRoute: typeof ApiProjectsIdRouteWithChildren
  ApiProjectsSearchRoute: typeof ApiProjectsSearchRoute
  ApiProjectsUserUserIdRoute: typeof ApiProjectsUserUserIdRoute
}

const ApiProjectsRouteChildren: ApiProjectsRouteChildren = {
  ApiProjectsIdRoute: ApiProjectsIdRouteWithChildren,
  ApiProjectsSearchRoute: ApiProjectsSearchRoute,
  ApiProjectsUserUserIdRoute: ApiProjectsUserUserIdRoute,
}

const ApiProjectsRouteWithChildren = ApiProjectsRoute._addFileChildren(
  ApiProjectsRouteChildren,
)

interface ApiUsersAvatarRouteChildren {
  ApiUsersAvatarIdRoute: typeof ApiUsersAvatarIdRoute
}

const ApiUsersAvatarRouteChildren: ApiUsersAvatarRouteChildren = {
  ApiUsersAvatarIdRoute: ApiUsersAvatarIdRoute,
}

const ApiUsersAvatarRouteWithChildren = ApiUsersAvatarRoute._addFileChildren(
  ApiUsersAvatarRouteChildren,
)

interface ApiUsersMessagesIdRouteChildren {
  ApiUsersMessagesIdReadRoute: typeof ApiUsersMessagesIdReadRoute
}

const ApiUsersMessagesIdRouteChildren: ApiUsersMessagesIdRouteChildren = {
  ApiUsersMessagesIdReadRoute: ApiUsersMessagesIdReadRoute,
}

const ApiUsersMessagesIdRouteWithChildren =
  ApiUsersMessagesIdRoute._addFileChildren(ApiUsersMessagesIdRouteChildren)

interface ApiUsersMessagesRouteChildren {
  ApiUsersMessagesIdRoute: typeof ApiUsersMessagesIdRouteWithChildren
}

const ApiUsersMessagesRouteChildren: ApiUsersMessagesRouteChildren = {
  ApiUsersMessagesIdRoute: ApiUsersMessagesIdRouteWithChildren,
}

const ApiUsersMessagesRouteWithChildren =
  ApiUsersMessagesRoute._addFileChildren(ApiUsersMessagesRouteChildren)

interface ApiUsersProfileRouteChildren {
  ApiUsersProfileImageRoute: typeof ApiUsersProfileImageRoute
  ApiUsersProfileMeRoute: typeof ApiUsersProfileMeRoute
}

const ApiUsersProfileRouteChildren: ApiUsersProfileRouteChildren = {
  ApiUsersProfileImageRoute: ApiUsersProfileImageRoute,
  ApiUsersProfileMeRoute: ApiUsersProfileMeRoute,
}

const ApiUsersProfileRouteWithChildren = ApiUsersProfileRoute._addFileChildren(
  ApiUsersProfileRouteChildren,
)

interface ApiUsersRouteChildren {
  ApiUsersIdRoute: typeof ApiUsersIdRoute
  ApiUsersAvatarRoute: typeof ApiUsersAvatarRouteWithChildren
  ApiUsersMessagesRoute: typeof ApiUsersMessagesRouteWithChildren
  ApiUsersProfileRoute: typeof ApiUsersProfileRouteWithChildren
  ApiUsersSearchRoute: typeof ApiUsersSearchRoute
}

const ApiUsersRouteChildren: ApiUsersRouteChildren = {
  ApiUsersIdRoute: ApiUsersIdRoute,
  ApiUsersAvatarRoute: ApiUsersAvatarRouteWithChildren,
  ApiUsersMessagesRoute: ApiUsersMessagesRouteWithChildren,
  ApiUsersProfileRoute: ApiUsersProfileRouteWithChildren,
  ApiUsersSearchRoute: ApiUsersSearchRoute,
}

const ApiUsersRouteWithChildren = ApiUsersRoute._addFileChildren(
  ApiUsersRouteChildren,
)

interface ApiAdminUsersIdRouteChildren {
  ApiAdminUsersIdRoleRoute: typeof ApiAdminUsersIdRoleRoute
  ApiAdminUsersIdSuspensionRoute: typeof ApiAdminUsersIdSuspensionRoute
}

const ApiAdminUsersIdRouteChildren: ApiAdminUsersIdRouteChildren = {
  ApiAdminUsersIdRoleRoute: ApiAdminUsersIdRoleRoute,
  ApiAdminUsersIdSuspensionRoute: ApiAdminUsersIdSuspensionRoute,
}

const ApiAdminUsersIdRouteWithChildren = ApiAdminUsersIdRoute._addFileChildren(
  ApiAdminUsersIdRouteChildren,
)

interface ApiAdminUsersRouteChildren {
  ApiAdminUsersIdRoute: typeof ApiAdminUsersIdRouteWithChildren
}

const ApiAdminUsersRouteChildren: ApiAdminUsersRouteChildren = {
  ApiAdminUsersIdRoute: ApiAdminUsersIdRouteWithChildren,
}

const ApiAdminUsersRouteWithChildren = ApiAdminUsersRoute._addFileChildren(
  ApiAdminUsersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  ApiEvaluationsRoute: ApiEvaluationsRouteWithChildren,
  ApiNotificationsRoute: ApiNotificationsRouteWithChildren,
  ApiProjectsRoute: ApiProjectsRouteWithChildren,
  ApiUsersRoute: ApiUsersRouteWithChildren,
  ApiAdminDashboardRoute: ApiAdminDashboardRoute,
  ApiAdminLogsRoute: ApiAdminLogsRoute,
  ApiAdminUsersRoute: ApiAdminUsersRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiGithubReposOwnerNameRoute: ApiGithubReposOwnerNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
